### ISSUE TITLE
Issue with extracting contents of example data

### ISSUE THREAD

**Issue by arjung128** [matterport/habitat-matterport-3dresearch#6]
I'm trying to extract the content of the example data, but I am running into the following errors:

```
~/habitat-matterport-3dresearch/example$ tar -xvf hm3d-example-configs.tar
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

~/habitat-matterport-3dresearch/example$ tar -zxvf hm3d-example-obj+mtl.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Any ideas why these files don't seem to be in the expected `.tar` and `.tar.gz` formats?

**Comment by sachal6** [comment]
The files themselves are healthy and do unpack as expected, you might be able to confirm this by manually downloading them from github's web interface rather than cloning the repo. The issue is likely with `git-lfs`.

If you install [git-lfs](https://git-lfs.github.com/) (remember to run `git lfs install` afterwards) and then attempt to re-clone the repo, do you still get the same error?
